openapi: 3.0.0
info:
  title: Serviço de Reservas (Seu Cantinho)
  description: API para gerenciamento de reservas e orquestração de validações.
  version: 1.0.0
servers:
  - url: http://localhost:3003
    description: Servidor Local
components:
  schemas:
    Reserva:
      type: object
      properties:
        id:
          type: string
          format: uuid
        idCliente:
          type: string
          format: uuid
        idEspaco:
          type: string
          format: uuid
        data:
          type: string
          format: date
          example: "2025-12-25"
        valor:
          type: number
        status:
          type: string
          enum: [PENDENTE, CONFIRMADA, CANCELADA]
    ReservaInput:
      type: object
      required:
        - idCliente
        - idEspaco
        - data
      properties:
        idCliente:
          type: string
        idEspaco:
          type: string
        data:
          type: string
          format: date
          description: "Formato YYYY-MM-DD"
paths:
  /reservas:
    get:
      summary: Listar todas as reservas
      tags: [Reservas]
      responses:
        200:
          description: Lista retornada com sucesso
    post:
      summary: Criar uma nova reserva
      description: Orquestra validação de usuário, espaço e gera pagamento.
      tags: [Reservas]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservaInput'
      responses:
        201:
          description: Reserva criada com sucesso (Pendente)
        400:
          description: Erro de validação ou conflito de data
        404:
          description: Cliente ou Espaço não encontrados
        502:
          description: Erro de comunicação com outros serviços
  /reservas/{id}:
    get:
      summary: Obter detalhes de uma reserva
      tags: [Reservas]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        200:
          description: Detalhes da reserva
    patch:
      summary: Atualizar status ou dados da reserva
      tags: [Reservas]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [CONFIRMADA, CANCELADA]
      responses:
        200:
          description: Reserva atualizada
    delete:
      summary: Cancelar/Remover reserva
      tags: [Reservas]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        204:
          description: Reserva removida